graph = {
    "Arad":           [("Zerind", 75), ("Timisoara", 118), ("Sibiu", 140)],
    "Zerind":         [("Arad", 75), ("Oradea", 71)],
    "Timisoara":      [("Arad", 118), ("Lugoj", 111)],
    "Sibiu":          [("Arad", 140), ("Oradea", 151), ("Fagaras", 99), ("Rimnicu Vilcea", 80)],
    "Oradea":         [("Zerind", 71), ("Sibiu", 151)],
    "Lugoj":          [("Timisoara", 111), ("Mehadia", 70)],
    "Fagaras":        [("Sibiu", 99), ("Bucharest", 211)],
    "Rimnicu Vilcea": [("Sibiu", 80), ("Pitesti", 97), ("Craiova", 146)],
    "Mehadia":        [("Lugoj", 70), ("Drobeta", 75)],
    "Bucharest":      [("Fagaras", 211), ("Pitesti", 101), ("Giurgiu", 90), ("Urziceni", 85)],
    "Pitesti":        [("Rimnicu Vilcea", 97), ("Craiova", 138), ("Bucharest", 101)],
    "Craiova":        [("Rimnicu Vilcea", 146), ("Drobeta", 120), ("Pitesti", 138)],
    "Drobeta":        [("Mehadia", 75), ("Craiova", 120)],
    "Giurgiu":        [("Bucharest", 90)],
    "Urziceni":       [("Bucharest", 85), ("Hirsova", 98), ("Vaslui", 142)],
    "Hirsova":        [("Urziceni", 98), ("Eforie", 86)],
    "Vaslui":         [("Urziceni", 142), ("Iasi", 92)],
    "Eforie":         [("Hirsova", 86)],
    "Iasi":           [("Vaslui", 92), ("Neamt", 87)],
    "Neamt":          [("Iasi", 87)]
}
